name: Copy to EC2

on:
  push:
    branches:
      - main

jobs:
  copy_to_ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        nvm install 16
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy code to EC2
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_IP }} "mkdir -p /home/youruser/yourapp"
        scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r . ubuntu@${{ secrets.EC2_IP }}:/home/youruser/yourapp
